=== ehcache/ehcache3/xml/src/main/resources/ehcache-core.xsd
<?xml version="1.0"?>
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<xs:schema version="1.0" xmlns:ehcache="http://www.ehcache.org/v3" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified" targetNamespace="http://www.ehcache.org/v3">
  <xs:element name="config" type="ehcache:config-type"/>

  <xs:complexType name="config-type">
    <xs:sequence>
      <xs:element name="service" type="ehcache:service-type" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Placeholder for services to be managed by the CacheManager and exposed to the Cache instances it manages.
            Those services will also be lifecycled by the CacheManager.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="cache" type="ehcache:cache-type">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              A cache definition the CacheManager will manage
            </xs:documentation>
          </xs:annotation>
          <xs:key name="template">
            <xs:selector xpath="cache-template"/>
            <xs:field xpath="@name"/>
          </xs:key>
        </xs:element>
        <xs:element name="cache-template" type="ehcache:cacheTemplate-type">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              A cache template definition that can be reference in &lt;cache&gt; definitions using the 'usesTemplate'
              attribute.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="service-type">
    <xs:choice>
      <xs:element name="serializer-default" type="ehcache:serializer-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="persistence" type="ehcache:persistence-type" minOccurs="0" maxOccurs="1"/>
      <xs:any namespace="##other" minOccurs="0" maxOccurs="1"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="persistence-type">
    <xs:sequence>
      <xs:element name="directory" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="serializer-type">
    <xs:sequence>
      <xs:element name="class" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute type="xs:string" name="cache" use="optional"/>
              <xs:attribute type="xs:string" name="type" use="optional"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
     </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="cache-type">
    <xs:complexContent>
      <xs:extension base="ehcache:baseCache-type">
        <xs:attribute name="alias" use="required" type="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              The alias used to access this Cache from the CacheManager
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="usesTemplate" use="optional" type="xs:IDREF">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              The optional &lt;cache-template&gt; to use to source a default configuration from.
              References the cache template's 'name' attribute.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="cacheTemplate-type" xml:base="ehcache:baseCache-type">
    <xs:complexContent>
      <xs:extension base="ehcache:baseCache-type">
        <xs:attribute name="name" type="xs:ID" use="required">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              The name of this &lt;cache-template&gt; definition.
              Used by cache element's 'usesTemplate' attribute.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="baseCache-type" abstract="true">
    <xs:sequence>
      <xs:element name="key-type" type="xs:string" minOccurs="0" maxOccurs="1" default="java.lang.Object">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Defines the type for the keys &lt;K&gt; of the Cache&lt;K, V&gt;. Takes a fully qualified class name.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="value-type" type="xs:string" minOccurs="0" maxOccurs="1" default="java.lang.Object">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Defines the type for the values &lt;V&gt; of the Cache&lt;K, V&gt;. Takes a fully qualified class name.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="expiry" type="ehcache:expiry-type" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Defines expiry for the Cache.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="eviction-veto" type="xs:string" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            A fully qualified class name to a concrete type that implements
            org.ehcache.config.EvictionVeto and has a public default no argument constructor.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="eviction-prioritizer" type="xs:string" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            A fully qualified class name to a concrete type that implements
            org.ehcache.config.EvictionPrioritizer and has a public default no argument constructor.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="integration" type="ehcache:cache-integration" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Configures the Cache as fronting a system of record that it'll be kept in sync with.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <!-- TODO The following choice is mandatory in a cache but optional in a template. Find the magic XSD incantation that does exactly that. -->
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element name="heap" type="ehcache:resource-type" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              Shortcut for configuring a heap-only Cache.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="resources" type="ehcache:resources-type" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              Configures the Cache resources.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:choice>
      <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="storeByValueOnHeap" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation xml:lang="en">
          Specifies whether the heap tier for this cache should store by value, if true; or by reference (default, false)
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="cache-integration">
    <xs:sequence>
      <xs:element name="loaderwriter" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="class" type="xs:string" minOccurs="1" maxOccurs="1">
              <xs:annotation>
                <xs:documentation xml:lang="en">
                  A fully qualified class name to a concrete type that implements
                  org.ehcache.spi.loaderwriter.CacheLoaderWriter and has a public
                  default no argument constructor.
                </xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="expiry-type">
    <xs:choice>
      <xs:element name="class" type="xs:string">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            A fully qualified class name to a concrete type that implements
            org.ehcache.expiry.Expiry and has a public default no argument constructor.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="tti" type="ehcache:time-type">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Entries in the cache should expire if not accessed for the defined time.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ttl" type="ehcache:time-type">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Entries in the cache should expire after the defined time.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="none">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Entries in the cache should never expire.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType/>
      </xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="time-type">
    <xs:simpleContent>
      <xs:extension base="xs:positiveInteger">
        <xs:attribute name="unit" type="ehcache:time-unit" default="seconds">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              The time unit (see java.util.concurrent.TimeUnit) this value is expressed in.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="resource-type">
    <xs:attribute name="unit" default="entries" use="optional"/>
    <xs:attribute name="size" use="required" type="xs:positiveInteger"/>
  </xs:complexType>

  <xs:complexType name="resources-type">
    <xs:sequence>
      <xs:element name="heap" type="ehcache:resource-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="disk" type="ehcache:resource-type" minOccurs="0" maxOccurs="1"/>
      <xs:any namespace="##other" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="time-unit">
    <xs:restriction base="xs:string">
      <xs:enumeration value="nanos"/>
      <xs:enumeration value="micros"/>
      <xs:enumeration value="millis"/>
      <xs:enumeration value="seconds"/>
      <xs:enumeration value="minutes"/>
      <xs:enumeration value="hours"/>
      <xs:enumeration value="days"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== ehcache/ehcache3/transactions/src/test/resources/configs/transactional-cache.xml
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<config
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xmlns='http://www.ehcache.org/v3'
  xmlns:tx='http://www.ehcache.org/v3/tx'
  xsi:schemaLocation="http://www.ehcache.org/v3 ../../../../../xml/src/main/resources/ehcache-core.xsd
                        http://www.ehcache.org/v3/tx ../../../main/resources/ehcache-tx-ext.xsd">

  <service>
    <tx:jta-tm
      transaction-manager-lookup-class="org.ehcache.transactions.xa.txmgr.btm.BitronixTransactionManagerLookup"/>
  </service>

  <cache alias="xaCache1">
    <key-type>java.lang.String</key-type>
    <value-type>java.lang.String</value-type>
    <expiry>
      <none/>
    </expiry>
    <resources>
      <heap unit="entries">20</heap>
    </resources>
    <tx:xa-store unique-XAResource-id="INVALID"/>
  </cache>

</config>

=== ehcache/ehcache3/xml/src/test/resources/configs/docs/getting-started.xml
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<!-- tag::gettingStarted[] -->
<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.ehcache.org/v3'
    xsi:schemaLocation="http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core.xsd">

  <cache alias="foo"> <!--1-->
    <key-type>java.lang.String</key-type> <!--2-->
    <value-type>java.lang.String</value-type> <!--2-->
    <resources>
      <heap unit="entries">20</heap> <!--3-->
      <offheap unit="MB">10</offheap> <!--4-->
    </resources>
  </cache>

  <cache-template name="myDefaults"> <!--5-->
    <key-type>java.lang.Long</key-type>
    <value-type>java.lang.String</value-type>
    <heap unit="entries">200</heap>
  </cache-template>

  <cache alias="bar" uses-template="myDefaults"> <!--6-->
    <key-type>java.lang.Number</key-type>
  </cache>

  <cache alias="simpleCache" uses-template="myDefaults" /> <!--7-->

</config>
<!-- end::gettingStarted[] -->

=== ehcache/ehcache3/xml/src/test/resources/configs/resources-templates.xml
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<ehcache:config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ehcache='http://www.ehcache.org/v3'
    xsi:schemaLocation="http://www.ehcache.org/v3 ../../../main/resources/ehcache-core.xsd">

  <ehcache:cache-template name="tieredResourceTemplate">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:resources>
      <ehcache:heap size="5"/>
      <ehcache:disk size="50"/>
    </ehcache:resources>
  </ehcache:cache-template>

  <ehcache:cache alias="templatedTieredResource" uses-template="tieredResourceTemplate">
  </ehcache:cache>

  <ehcache:cache-template name="persistentTieredResourceTemplate">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:resources>
      <ehcache:heap size="5"/>
      <ehcache:disk size="50" persistent="true"/>
    </ehcache:resources>
  </ehcache:cache-template>

  <ehcache:cache alias="persistentTemplatedTieredResource" uses-template="persistentTieredResourceTemplate">
  </ehcache:cache>

  <ehcache:cache-template name="tieredOffHeapResourceTemplate">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:resources>
      <ehcache:heap size="5"/>
      <ehcache:offheap size="50" unit="mb"/>
    </ehcache:resources>
  </ehcache:cache-template>

  <ehcache:cache alias="templatedOffHeapTieredResource" uses-template="tieredOffHeapResourceTemplate">
  </ehcache:cache>

  <ehcache:cache-template name="explicitHeapResourceTemplate">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:resources>
      <ehcache:heap size="15"/>
    </ehcache:resources>
  </ehcache:cache-template>

  <ehcache:cache alias="templatedExplicitHeapResource" uses-template="explicitHeapResourceTemplate">
  </ehcache:cache>

  <ehcache:cache-template name="implicitHeapResourceTemplate">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
  </ehcache:cache-template>

  <ehcache:cache alias="templatedImplicitHeapResource" uses-template="implicitHeapResourceTemplate">
  </ehcache:cache>

</ehcache:config>
