=== ehcache/ehcache3/xml/src/main/resources/ehcache-core.xsd
<?xml version="1.0"?>
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<xs:schema version="1.0" xmlns:ehcache="http://www.ehcache.org/v3" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified" targetNamespace="http://www.ehcache.org/v3">
  <xs:element name="config" type="ehcache:config-type"/>

  <xs:complexType name="config-type">
    <xs:sequence>
      <xs:element name="service" type="ehcache:service-type" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Placeholder for services to be managed by the CacheManager and exposed to the Cache instances it manages.
            Those services will also be lifecycled by the CacheManager.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="cache" type="ehcache:cache-type">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              A cache definition the CacheManager will manage
            </xs:documentation>
          </xs:annotation>
          <xs:key name="template">
            <xs:selector xpath="cache-template"/>
            <xs:field xpath="@name"/>
          </xs:key>
        </xs:element>
        <xs:element name="cache-template" type="ehcache:cacheTemplate-type">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              A cache template definition that can be reference in &lt;cache&gt; definitions using the 'usesTemplate'
              attribute.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="service-type">
    <xs:choice>
      <xs:element name="serializer-default" type="ehcache:serializer-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="persistence" type="ehcache:persistence-type" minOccurs="0" maxOccurs="1"/>
      <xs:any namespace="##other" minOccurs="0" maxOccurs="1"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="persistence-type">
    <xs:sequence>
      <xs:element name="directory" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="serializer-type">
    <xs:sequence>
      <xs:element name="class" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute type="xs:string" name="cache" use="optional"/>
              <xs:attribute type="xs:string" name="type" use="optional"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
     </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="cache-type">
    <xs:complexContent>
      <xs:extension base="ehcache:baseCache-type">
        <xs:attribute name="alias" use="required" type="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              The alias used to access this Cache from the CacheManager
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="usesTemplate" use="optional" type="xs:IDREF">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              The optional &lt;cache-template&gt; to use to source a default configuration from.
              References the cache template's 'name' attribute.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="cacheTemplate-type" xml:base="ehcache:baseCache-type">
    <xs:complexContent>
      <xs:extension base="ehcache:baseCache-type">
        <xs:attribute name="name" type="xs:ID" use="required">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              The name of this &lt;cache-template&gt; definition.
              Used by cache element's 'usesTemplate' attribute.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="baseCache-type" abstract="true">
    <xs:sequence>
      <xs:element name="key-type" type="xs:string" minOccurs="0" maxOccurs="1" default="java.lang.Object">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Defines the type for the keys &lt;K&gt; of the Cache&lt;K, V&gt;. Takes a fully qualified class name.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="value-type" type="xs:string" minOccurs="0" maxOccurs="1" default="java.lang.Object">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Defines the type for the values &lt;V&gt; of the Cache&lt;K, V&gt;. Takes a fully qualified class name.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="expiry" type="ehcache:expiry-type" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Defines expiry for the Cache.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="eviction-veto" type="xs:string" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            A fully qualified class name to a concrete type that implements
            org.ehcache.config.EvictionVeto and has a public default no argument constructor.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="eviction-prioritizer" type="xs:string" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            A fully qualified class name to a concrete type that implements
            org.ehcache.config.EvictionPrioritizer and has a public default no argument constructor.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="integration" type="ehcache:cache-integration" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Configures the Cache as fronting a system of record that it'll be kept in sync with.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <!-- TODO The following choice is mandatory in a cache but optional in a template. Find the magic XSD incantation that does exactly that. -->
      <xs:choice minOccurs="0" maxOccurs="1">
        <xs:element name="heap" type="ehcache:resource-type" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              Shortcut for configuring a heap-only Cache.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="resources" type="ehcache:resources-type" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              Configures the Cache resources.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:choice>
      <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="storeByValueOnHeap" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation xml:lang="en">
          Specifies whether the heap tier for this cache should store by value, if true; or by reference (default, false)
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="cache-integration">
    <xs:sequence>
      <xs:element name="loaderwriter" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="class" type="xs:string" minOccurs="1" maxOccurs="1">
              <xs:annotation>
                <xs:documentation xml:lang="en">
                  A fully qualified class name to a concrete type that implements
                  org.ehcache.spi.loaderwriter.CacheLoaderWriter and has a public
                  default no argument constructor.
                </xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="expiry-type">
    <xs:choice>
      <xs:element name="class" type="xs:string">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            A fully qualified class name to a concrete type that implements
            org.ehcache.expiry.Expiry and has a public default no argument constructor.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="tti" type="ehcache:time-type">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Entries in the cache should expire if not accessed for the defined time.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="ttl" type="ehcache:time-type">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Entries in the cache should expire after the defined time.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="none">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            Entries in the cache should never expire.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType/>
      </xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="time-type">
    <xs:simpleContent>
      <xs:extension base="xs:positiveInteger">
        <xs:attribute name="unit" type="ehcache:time-unit" default="seconds">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              The time unit (see java.util.concurrent.TimeUnit) this value is expressed in.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="resource-type">
    <xs:attribute name="unit" default="entries" use="optional"/>
    <xs:attribute name="size" use="required" type="xs:positiveInteger"/>
  </xs:complexType>

  <xs:complexType name="resources-type">
    <xs:sequence>
      <xs:element name="heap" type="ehcache:resource-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="disk" type="ehcache:resource-type" minOccurs="0" maxOccurs="1"/>
      <xs:any namespace="##other" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="time-unit">
    <xs:restriction base="xs:string">
      <xs:enumeration value="nanos"/>
      <xs:enumeration value="micros"/>
      <xs:enumeration value="millis"/>
      <xs:enumeration value="seconds"/>
      <xs:enumeration value="minutes"/>
      <xs:enumeration value="hours"/>
      <xs:enumeration value="days"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== ehcache/ehcache3/107/src/test/resources/ehcache-107-stats.xml
<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.ehcache.org/v3'
    xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
    xsi:schemaLocation="http://www.ehcache.org/v3 ../../../../xml/src/main/resources/ehcache-core.xsd
                        http://www.ehcache.org/v3/jsr107 ../../main/resources/ehcache-107ext.xsd">

  <service>
    <jsr107:defaults>
      <jsr107:cache name="heap" template="heapCache"/>
      <jsr107:cache name="offheap" template="offheapCache"/>
      <jsr107:cache name="disk" template="diskCache"/>
    </jsr107:defaults>
  </service>

  <persistence directory="build/ehcache-107-stats"/>
  
  <cache-template name="diskCache">
    <resources>
      <heap unit="entries">10</heap>
      <disk unit="MB">10</disk>
    </resources>
  </cache-template>
  
  <cache-template name="offheapCache">
    <resources>
      <heap unit="entries">10</heap>
      <offheap unit="MB">10</offheap>
    </resources>
  </cache-template>

  <cache-template name="heapCache">
    <key-type>java.lang.String</key-type>
    <value-type>java.lang.String</value-type>
    <heap unit="entries">10</heap>
  </cache-template>

</config>

=== ehcache/ehcache3/xml/src/test/resources/configs/disk-persistent-cache.xml
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<config
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xmlns='http://www.ehcache.org/v3'
  xsi:schemaLocation="http://www.ehcache.org/v3 ../../../main/resources/ehcache-core.xsd">

  <persistence directory="some/dir"/>
  <disk-store thread-pool="pool-disk"/>

  <cache alias="test">
    <key-type>java.lang.String</key-type>
    <value-type>java.lang.String</value-type>
    <resources>
      <heap unit="MB">100</heap>
      <disk unit="GB" persistent="true">100</disk>
    </resources>
    <disk-store-settings thread-pool="pool-disk" writer-concurrency="10" disk-segments="2"/>
  </cache>
</config>

=== ehcache/ehcache3/xml/src/test/resources/configs/persistence-mode-cache.xml
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
  
<ehcache:config
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xmlns:ehcache='http://www.ehcache.org/v3'
  xsi:schemaLocation="http://www.ehcache.org/v3 ../../../main/resources/ehcache-core.xsd">
  
  <ehcache:cache alias="tiered">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:persistence-mode>create_if_absent</ehcache:persistence-mode>
    <ehcache:resources>
      <ehcache:heap size="10" unit="entries"/>
      <ehcache:disk size="100" unit="entries"/>
    </ehcache:resources>
  </ehcache:cache>
  
  <ehcache:cache-template name="tieredTemplate">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:persistence-mode>create_if_absent</ehcache:persistence-mode>
    <ehcache:resources>
      <ehcache:heap size="5"/>
      <ehcache:disk size="50"/>
    </ehcache:resources>
  </ehcache:cache-template>
  
</ehcache:config>

=== ehcache/ehcache3/osgi-test/src/test/resources/org/ehcache/osgi/ehcache-107-osgi.xml
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.ehcache.org/v3'
    xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
    xsi:schemaLocation="http://www.ehcache.org/v3 ../../../../../../../xml/src/main/resources/ehcache-core.xsd
                        http://www.ehcache.org/v3/jsr107 ../../../../../../../107/src/main/resources/ehcache-107-ext.xsd">
  <service>
    <jsr107:defaults default-template="tinyCache">
      <jsr107:cache name="foos" template="stringCache"/>
    </jsr107:defaults>
  </service>

  <cache alias="personCache">
    <key-type>java.lang.Long</key-type>
    <value-type>org.ehcache.osgi.Person</value-type>
    <heap>10</heap>
  </cache>

  <cache-template name="stringCache">
    <key-type>java.lang.String</key-type>
    <value-type>Person</value-type>
    <heap unit="entries">2000</heap>
  </cache-template>
  <cache-template name="tinyCache">
    <heap unit="entries">20</heap>
  </cache-template>
</config>

=== ehcache/ehcache3/xml/src/test/resources/configs/default-serializer.xml
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<ehcache:config
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xmlns:ehcache='http://www.ehcache.org/v3'
  xsi:schemaLocation=" http://www.ehcache.org/v3 ../../../main/resources/ehcache-core.xsd">

  <ehcache:service>
    <ehcache:serializer-default>
      <ehcache:serializer>com.pany.ehcache.serializer.TestSerializer</ehcache:serializer>
    </ehcache:serializer-default>
  </ehcache:service>


  <ehcache:cache alias="bar" storeByValueOnHeap="true">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:heap size="10"/>
  </ehcache:cache>
</ehcache:config>

=== ehcache/ehcache3/xml/src/test/resources/configs/expiry-caches.xml
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<ehcache:config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ehcache='http://www.ehcache.org/v3'
    xsi:schemaLocation="http://www.ehcache.org/v3 ../../../main/resources/ehcache-core.xsd">

  <ehcache:cache alias="class">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:expiry>
      <ehcache:class>com.pany.ehcache.MyExpiry</ehcache:class>
    </ehcache:expiry>
    <ehcache:heap>5</ehcache:heap>
  </ehcache:cache>

  <ehcache:cache alias="deprecatedClass">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:expiry>
      <ehcache:class>com.pany.ehcache.DeprecatedExpiry</ehcache:class>
    </ehcache:expiry>
    <ehcache:heap>5</ehcache:heap>
  </ehcache:cache>

  <ehcache:cache alias="none">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:expiry>
      <ehcache:none/>
    </ehcache:expiry>
    <ehcache:heap>5</ehcache:heap>
  </ehcache:cache>

  <ehcache:cache alias="tti">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:expiry>
      <ehcache:tti unit="millis">500</ehcache:tti>
    </ehcache:expiry>
    <ehcache:heap>5</ehcache:heap>
  </ehcache:cache>

  <ehcache:cache alias="ttl">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:expiry>
      <ehcache:ttl>30</ehcache:ttl>
    </ehcache:expiry>
    <ehcache:heap>5</ehcache:heap>
  </ehcache:cache>

  <ehcache:cache alias="notSet">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:heap>5</ehcache:heap>
  </ehcache:cache>
</ehcache:config>

=== ehcache/ehcache3/xml/src/test/resources/configs/ehcache-serializer.xml
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<ehcache:config xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	xmlns:ehcache='http://www.ehcache.org/v3'
	xsi:schemaLocation="http://www.ehcache.org/v3 ../../../main/resources/ehcache-core.xsd">

	<ehcache:service>
    <ehcache:serializer-default>
      <ehcache:class type="java.lang.Number">com.pany.ehcache.serializer.TestSerializer</ehcache:class>
      <ehcache:class type="java.lang.Number" cache="foo">com.pany.ehcache.serializer.TestSerializer</ehcache:class>
      <ehcache:class type="java.lang.Number" cache="bar">com.pany.ehcache.serializer.TestSerializer</ehcache:class>
      <ehcache:class type="java.lang.String">com.pany.ehcache.serializer.TestSerializer</ehcache:class>
    </ehcache:serializer-default>
	</ehcache:service>

	<ehcache:cache-template name="example">
	</ehcache:cache-template>

	<ehcache:cache alias="foo">
	</ehcache:cache>

	<ehcache:cache alias="bar" usesTemplate="example">
		<ehcache:key-type>java.lang.Number</ehcache:key-type>
	</ehcache:cache>
</ehcache:config>

=== ehcache/ehcache3/xml/src/test/resources/configs/resources-caches.xml
<!--
  ~ Copyright Terracotta, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<ehcache:config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ehcache='http://www.ehcache.org/v3'
    xsi:schemaLocation="http://www.ehcache.org/v3 ../../../main/resources/ehcache-core.xsd">

  <ehcache:disk-store thread-pool="disk-pool"/>

  <ehcache:cache alias="tiered">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:resources>
      <ehcache:heap unit="entries">10</ehcache:heap>
      <ehcache:disk unit="MB">100</ehcache:disk>
    </ehcache:resources>
    <ehcache:disk-store-settings writer-concurrency="2" thread-pool="some-pool" disk-segments="4"/>
  </ehcache:cache>

  <ehcache:cache alias="tieredPersistent">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:resources>
      <ehcache:heap unit="entries">10</ehcache:heap>
      <ehcache:disk unit="MB" persistent="true">100</ehcache:disk>
    </ehcache:resources>
  </ehcache:cache>

  <ehcache:cache alias="tieredOffHeap">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:resources>
      <ehcache:heap unit="entries">10</ehcache:heap>
      <ehcache:offheap unit="MB">10</ehcache:offheap>
    </ehcache:resources>
  </ehcache:cache>

  <ehcache:cache alias="explicitHeapOnly">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:resources>
      <ehcache:heap unit="entries">15</ehcache:heap>
    </ehcache:resources>
  </ehcache:cache>

  <ehcache:cache alias="directHeapOnly">
    <ehcache:key-type>java.lang.String</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:heap unit="entries">25</ehcache:heap>
  </ehcache:cache>

</ehcache:config>
